// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5gryfkuxZmpJ2zLMO4tgTH2F3nYd21og',
    appId: '1:885213847275:web:204da715105f64b8a5a8ae',
    messagingSenderId: '885213847275',
    projectId: 'ecommerce-f8c38',
    authDomain: 'ecommerce-f8c38.firebaseapp.com',
    storageBucket: 'ecommerce-f8c38.firebasestorage.app',
    measurementId: 'G-D9HDBQ89GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDuPIUp88gfSdLjNoUYznMGnB4kdj4lkM',
    appId: '1:885213847275:android:2a6bb99c8147479da5a8ae',
    messagingSenderId: '885213847275',
    projectId: 'ecommerce-f8c38',
    storageBucket: 'ecommerce-f8c38.firebasestorage.app',
  );
}
